/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<number, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AccessTokens {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  customer_id: string | null;
  expires_at: Timestamp;
  id: Generated<string>;
  last_used_at: Timestamp | null;
  max_uses: number | null;
  organization_id: string;
  purpose: string;
  resource_id: string;
  resource_type: string;
  revoked_at: Timestamp | null;
  token_hash: string;
  use_count: Generated<number>;
}

export interface AiSuggestions {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  decided_at: Timestamp | null;
  decided_by: string | null;
  id: Generated<string>;
  input: Generated<Json>;
  kind: string;
  model: string | null;
  organization_id: string;
  output: Generated<Json>;
  provider: string;
  status: Generated<string>;
  subject_id: string | null;
  subject_type: string;
}

export interface AnalyticsDailyMenu {
  computed_at: Generated<Timestamp>;
  count: Generated<number>;
  date: string;
  menu_id: string;
  organization_id: string;
  sales: Generated<number>;
  shop_id: string;
}

export interface AnalyticsDailyShop {
  appointment_count: Generated<number>;
  cancel_count: Generated<number>;
  computed_at: Generated<Timestamp>;
  customer_count: Generated<number>;
  date: string;
  discount_total: Generated<number>;
  new_customer_count: Generated<number>;
  no_show_count: Generated<number>;
  nominated_count: Generated<number>;
  organization_id: string;
  product_sales: Generated<number>;
  refund_total: Generated<number>;
  repeat_customer_count: Generated<number>;
  sales_total: Generated<number>;
  service_sales: Generated<number>;
  shop_id: string;
  tax_total: Generated<number>;
  transaction_count: Generated<number>;
}

export interface AnalyticsDailySource {
  appointment_count: Generated<number>;
  completed_count: Generated<number>;
  computed_at: Generated<Timestamp>;
  date: string;
  organization_id: string;
  sales: Generated<number>;
  shop_id: string;
  source: string;
}

export interface AnalyticsDailyStaff {
  booked_minutes: Generated<number>;
  computed_at: Generated<Timestamp>;
  customer_count: Generated<number>;
  date: string;
  new_customer_count: Generated<number>;
  nominated_count: Generated<number>;
  organization_id: string;
  product_sales: Generated<number>;
  sales_total: Generated<number>;
  scheduled_minutes: Generated<number>;
  service_sales: Generated<number>;
  shop_id: string;
  staff_id: string;
}

export interface AppointmentEvents {
  actor_id: string | null;
  actor_type: string;
  appointment_id: string;
  created_at: Generated<Timestamp>;
  event_type: string;
  id: Generated<string>;
  organization_id: string;
  payload: Generated<Json>;
  trace_id: string | null;
}

export interface AppointmentResources {
  appointment_id: string;
  end_at: Timestamp;
  id: Generated<string>;
  is_active: Generated<boolean>;
  organization_id: string;
  resource_id: string;
  start_at: Timestamp;
}

export interface Appointments {
  booking_reference: string;
  cancel_reason: string | null;
  cancelled_at: Timestamp | null;
  cancelled_by_type: string | null;
  checked_in_at: Timestamp | null;
  completed_at: Timestamp | null;
  confirmed_at: Timestamp | null;
  coupon_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  customer_id: string | null;
  customer_note: string | null;
  deleted_at: Timestamp | null;
  end_at: Timestamp;
  estimated_total: Generated<number>;
  id: Generated<string>;
  is_consultation: Generated<boolean>;
  is_nominated: Generated<boolean>;
  no_show_at: Timestamp | null;
  occupied_end_at: Timestamp;
  occupied_start_at: Timestamp;
  organization_id: string;
  shop_id: string;
  source: Generated<string>;
  source_detail: Generated<Json>;
  staff_id: string | null;
  staff_note: string | null;
  start_at: Timestamp;
  status: Generated<string>;
  trace_id: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  version: Generated<number>;
}

export interface AppointmentServices {
  appointment_id: string;
  created_at: Generated<Timestamp>;
  duration_min: number;
  id: Generated<string>;
  menu_id: string | null;
  name: string;
  organization_id: string;
  price: number;
  sort_order: Generated<number>;
  staff_id: string | null;
  start_offset_min: Generated<number>;
  tax_rate_bp: Generated<number>;
}

export interface AuditLogs {
  action: string;
  actor_id: string | null;
  actor_type: string;
  actor_user_id: string | null;
  after: Json | null;
  before: Json | null;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  ip: string | null;
  metadata: Generated<Json>;
  organization_id: string | null;
  request_id: string | null;
  resource_id: string | null;
  resource_type: string;
  shop_id: string | null;
  trace_id: string | null;
  user_agent: string | null;
}

export interface AuthSessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  ip: string | null;
  last_used_at: Timestamp | null;
  organization_id: string;
  refresh_token_hash: string;
  revoked_at: Timestamp | null;
  rotated_from: string | null;
  staff_id: string;
  user_agent: string | null;
  user_id: string;
}

export interface AutomationRuns {
  automation_id: string;
  created_at: Generated<Timestamp>;
  customer_id: string;
  dedupe_key: string;
  id: Generated<string>;
  message_id: string | null;
  organization_id: string;
}

export interface Automations {
  channel: Generated<string>;
  config: Generated<Json>;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  last_run_at: Timestamp | null;
  name: string;
  organization_id: string;
  shop_id: string | null;
  template_id: string | null;
  trigger_type: string;
  updated_at: Generated<Timestamp>;
}

export interface Campaigns {
  approved_at: Timestamp | null;
  approved_by: string | null;
  body: string | null;
  channel: Generated<string>;
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  name: string;
  organization_id: string;
  scheduled_at: Timestamp | null;
  segment_id: string | null;
  segment_rule: Json;
  shop_id: string | null;
  started_at: Timestamp | null;
  stats: Generated<Json>;
  status: Generated<string>;
  template_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface Counters {
  organization_id: string;
  scope: string;
  value: Generated<number>;
}

export interface CouponRedemptions {
  appointment_id: string | null;
  coupon_id: string;
  created_at: Generated<Timestamp>;
  customer_id: string | null;
  id: Generated<string>;
  organization_id: string;
  status: Generated<string>;
  transaction_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface Coupons {
  applicable_menu_ids: Generated<string[]>;
  code: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  description: string | null;
  discount_type: string;
  discount_value: number;
  id: Generated<string>;
  is_public: Generated<boolean>;
  min_amount: Generated<number>;
  name: string;
  new_customer_only: Generated<boolean>;
  organization_id: string;
  per_customer_limit: number | null;
  shop_id: string | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  usage_limit: number | null;
  valid_from: Timestamp | null;
  valid_until: Timestamp | null;
}

export interface CustomerChannelPreferences {
  channel: string;
  customer_id: string;
  marketing_allowed: Generated<boolean>;
  organization_id: string;
  source: string | null;
  transactional_allowed: Generated<boolean>;
  updated_at: Generated<Timestamp>;
}

export interface CustomerDuplicateDismissals {
  created_at: Generated<Timestamp>;
  customer_a_id: string;
  customer_b_id: string;
  dismissed_by: string | null;
  organization_id: string;
}

export interface CustomerIdentities {
  created_at: Generated<Timestamp>;
  customer_id: string;
  display_name: string | null;
  external_id: string;
  id: Generated<string>;
  is_following: boolean | null;
  linked_at: Generated<Timestamp>;
  organization_id: string;
  profile: Generated<Json>;
  provider: string;
  provider_account_id: Generated<string>;
  unlinked_at: Timestamp | null;
  updated_at: Generated<Timestamp>;
}

export interface CustomerMemos {
  body: string;
  created_at: Generated<Timestamp>;
  customer_id: string;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  organization_id: string;
  pinned: Generated<boolean>;
  staff_id: string;
  updated_at: Generated<Timestamp>;
  visibility: Generated<string>;
}

export interface CustomerMergeLogs {
  id: Generated<string>;
  match_rule: string | null;
  merged_at: Generated<Timestamp>;
  merged_by: string | null;
  organization_id: string;
  reason: string | null;
  relinked: Generated<Json>;
  source_customer_id: string;
  source_snapshot: Json;
  target_customer_id: string;
  target_snapshot: Json;
  undone_at: Timestamp | null;
  undone_by: string | null;
}

export interface Customers {
  acquisition_source: string | null;
  address: string | null;
  attributes: Generated<Json>;
  avg_cycle_days: Numeric | null;
  birthday: string | null;
  cancel_count: Generated<number>;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  customer_number: string | null;
  deleted_at: Timestamp | null;
  email: string | null;
  first_name: Generated<string>;
  first_name_kana: Generated<string>;
  first_visit_at: Timestamp | null;
  gender: string | null;
  id: Generated<string>;
  last_name: Generated<string>;
  last_name_kana: Generated<string>;
  last_visit_at: Timestamp | null;
  marketing_opt_in: Generated<boolean>;
  merged_into_id: string | null;
  next_appointment_at: Timestamp | null;
  no_show_count: Generated<number>;
  occupation: string | null;
  organization_id: string;
  phone: string | null;
  phone_normalized: string | null;
  point_balance: Generated<number>;
  postal_code: string | null;
  primary_shop_id: string | null;
  primary_staff_id: string | null;
  search_text: Generated<string | null>;
  status: Generated<string>;
  total_sales: Generated<number>;
  trace_id: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  visit_count: Generated<number>;
}

export interface CustomerScores {
  churn_risk: Numeric;
  churn_risk_level: string;
  computed_at: Generated<Timestamp>;
  customer_id: string;
  expected_ltv_12m: number | null;
  features: Generated<Json>;
  model_version: string;
  organization_id: string;
  predicted_next_visit: string | null;
  recommended_action: string | null;
}

export interface CustomerShopRelations {
  created_at: Generated<Timestamp>;
  customer_id: string;
  end_reason: string | null;
  ended_at: Timestamp | null;
  id: Generated<string>;
  organization_id: string;
  relation_type: string;
  shop_id: string;
  staff_id: string | null;
  started_at: Generated<Timestamp>;
  updated_at: Generated<Timestamp>;
}

export interface CustomerTags {
  created_at: Generated<Timestamp>;
  customer_id: string;
  organization_id: string;
  tag_id: string;
}

export interface CustomPaymentMethods {
  counts_as_sales: Generated<boolean>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  organization_id: string;
  shop_id: string | null;
}

export interface DataExports {
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  error: string | null;
  expires_at: Timestamp | null;
  file_id: string | null;
  id: Generated<string>;
  kind: string;
  organization_id: string;
  params: Generated<Json>;
  requested_by: string;
  row_count: number | null;
  status: Generated<string>;
}

export interface DomainEvents {
  actor_id: string | null;
  aggregate_id: string;
  aggregate_type: string;
  created_at: Generated<Timestamp>;
  event_type: string;
  id: Generated<number>;
  organization_id: string;
  payload: Generated<Json>;
  trace_id: string | null;
}

export interface ExternalBookings {
  appointment_id: string | null;
  created_at: Generated<Timestamp>;
  external_booking_id: string;
  external_status: string;
  external_updated_at: Timestamp | null;
  id: Generated<string>;
  integration_account_id: string;
  last_error: string | null;
  last_synced_at: Timestamp | null;
  normalized: Json;
  organization_id: string;
  payload_hash: string;
  provider: string;
  raw_payload: Json;
  sync_state: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface ExternalSlotBlocks {
  appointment_id: string;
  attempts: Generated<number>;
  block_end_at: Timestamp | null;
  block_start_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  done_at: Timestamp | null;
  done_by: string | null;
  external_block_id: string | null;
  id: Generated<string>;
  integration_account_id: string;
  last_error: string | null;
  manual: Generated<boolean>;
  notified_at: Timestamp | null;
  organization_id: string;
  pushed_at: Timestamp | null;
  staff_external_id: string | null;
  state: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface FeatureFlags {
  description: string | null;
  enabled: Generated<boolean>;
  id: Generated<string>;
  key: string;
  organization_id: string | null;
  rollout: Generated<Json>;
  updated_at: Generated<Timestamp>;
}

export interface Files {
  checksum_sha256: string | null;
  content_type: string;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  deleted_by: string | null;
  file_name: string | null;
  id: Generated<string>;
  object_key: string;
  organization_id: string;
  purpose: string;
  size_bytes: number | null;
  status: Generated<string>;
  uploaded_at: Timestamp | null;
  uploaded_by: string | null;
}

export interface FormResponses {
  answers: Generated<Json>;
  appointment_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  customer_id: string;
  document_hash: string | null;
  id: Generated<string>;
  ip: string | null;
  karte_id: string | null;
  organization_id: string;
  shop_id: string | null;
  signature_file_id: string | null;
  signed_at: Timestamp | null;
  signer_name: string | null;
  status: Generated<string>;
  submitted_at: Timestamp | null;
  submitted_via: string | null;
  template_id: string;
  template_snapshot: Json;
  template_version: number;
  updated_at: Generated<Timestamp>;
  user_agent: string | null;
  void_reason: string | null;
  voided_at: Timestamp | null;
  voided_by: string | null;
}

export interface FormTemplates {
  body_markdown: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  fields: Generated<Json>;
  id: Generated<string>;
  kind: string;
  lineage_id: string;
  name: string;
  organization_id: string;
  requires_signature: Generated<boolean>;
  shop_id: string | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  version: Generated<number>;
}

export interface IdempotencyKeys {
  created_at: Generated<Timestamp>;
  expires_at: Generated<Timestamp>;
  id: Generated<string>;
  key: string;
  organization_id: string;
  request_hash: string;
  response_body: Json | null;
  response_status: number | null;
  scope: string;
  state: Generated<string>;
}

export interface IntegrationAccounts {
  config: Generated<Json>;
  consecutive_failures: Generated<number>;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  display_name: string;
  encrypted_credentials: string | null;
  id: Generated<string>;
  last_error: string | null;
  last_error_at: Timestamp | null;
  last_success_at: Timestamp | null;
  last_synced_at: Timestamp | null;
  organization_id: string;
  provider: string;
  shop_id: string | null;
  status: Generated<string>;
  sync_cursor: string | null;
  updated_at: Generated<Timestamp>;
}

export interface Jobs {
  attempts: Generated<number>;
  created_at: Generated<Timestamp>;
  dedupe_key: string | null;
  finished_at: Timestamp | null;
  id: Generated<string>;
  last_error: string | null;
  locked_at: Timestamp | null;
  locked_by: string | null;
  max_attempts: Generated<number>;
  organization_id: string | null;
  payload: Generated<Json>;
  priority: Generated<number>;
  queue: Generated<string>;
  run_at: Generated<Timestamp>;
  state: Generated<string>;
  trace_id: string | null;
  type: string;
}

export interface KarteAssets {
  asset_type: string;
  caption: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  customer_id: string;
  deleted_at: Timestamp | null;
  file_id: string;
  id: Generated<string>;
  karte_id: string;
  object_key: string;
  organization_id: string;
  share_with_customer: Generated<boolean>;
  sort_order: Generated<number>;
}

export interface Kartes {
  appointment_id: string | null;
  chemicals: Generated<Json>;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  customer_id: string;
  deleted_at: Timestamp | null;
  fields: Generated<Json>;
  homecare: Generated<Json>;
  id: Generated<string>;
  note: string | null;
  organization_id: string;
  shared_at: Timestamp | null;
  shared_with_customer: Generated<boolean>;
  shop_id: string;
  staff_id: string;
  template_id: string | null;
  trace_id: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  version: Generated<number>;
  visit_date: string;
}

export interface KarteTemplates {
  category: string | null;
  created_at: Generated<Timestamp>;
  fields: Generated<Json>;
  id: Generated<string>;
  is_default: Generated<boolean>;
  name: string;
  organization_id: string;
  shop_id: string | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface LineChannels {
  basic_id: string | null;
  bot_user_id: string | null;
  channel_id: string;
  created_at: Generated<Timestamp>;
  encrypted_access_token: string;
  encrypted_channel_secret: string;
  id: Generated<string>;
  liff_id: string | null;
  login_channel_id: string | null;
  name: string;
  organization_id: string;
  shop_id: string | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  webhook_verified_at: Timestamp | null;
}

export interface MenuCategories {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  name: string;
  organization_id: string;
  shop_id: string | null;
  sort_order: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface MenuResourceRequirements {
  created_at: Generated<Timestamp>;
  duration_min: number | null;
  id: Generated<string>;
  menu_id: string;
  offset_min: Generated<number>;
  organization_id: string;
  resource_type: string;
}

export interface Menus {
  buffer_after_min: Generated<number>;
  buffer_before_min: Generated<number>;
  category_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  deleted_at: Timestamp | null;
  description: string | null;
  duration_min: number;
  id: Generated<string>;
  image_file_id: string | null;
  is_consultation: Generated<boolean>;
  is_public: Generated<boolean>;
  name: string;
  new_customer_only: Generated<boolean>;
  organization_id: string;
  price: number;
  price_tax_included: Generated<boolean>;
  shop_id: string | null;
  sort_order: Generated<number>;
  status: Generated<string>;
  tax_rate_bp: Generated<number>;
  trace_id: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface MenuShopOverrides {
  created_at: Generated<Timestamp>;
  duration_min: number | null;
  id: Generated<string>;
  is_available: Generated<boolean>;
  menu_id: string;
  organization_id: string;
  price: number | null;
  shop_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Messages {
  appointment_id: string | null;
  attempts: Generated<number>;
  automation_id: string | null;
  body: string | null;
  campaign_id: string | null;
  category: Generated<string>;
  channel: string;
  created_at: Generated<Timestamp>;
  customer_id: string | null;
  dedupe_key: string | null;
  direction: string;
  error: string | null;
  id: Generated<string>;
  line_channel_id: string | null;
  message_type: Generated<string>;
  next_attempt_at: Timestamp | null;
  organization_id: string;
  payload: Json | null;
  provider_message_id: string | null;
  read_at: Timestamp | null;
  recipient: string | null;
  scheduled_at: Timestamp | null;
  sent_at: Timestamp | null;
  sent_by_staff_id: string | null;
  shop_id: string | null;
  skip_reason: string | null;
  status: Generated<string>;
  template_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface MessageTemplates {
  body: string;
  category: string;
  channel: Generated<string>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  key: string | null;
  name: string;
  organization_id: string;
  payload: Json | null;
  shop_id: string | null;
  status: Generated<string>;
  subject: string | null;
  updated_at: Generated<Timestamp>;
}

export interface MockProviderBlocks {
  created_at: Generated<Timestamp>;
  id: string;
  integration_account_id: string;
  organization_id: string;
  payload: Json;
  removed_at: Timestamp | null;
}

export interface MockProviderBookings {
  change_seq: Generated<number>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  integration_account_id: string;
  organization_id: string;
  payload: Json;
  reserve_id: string;
  start_at: Timestamp;
  updated_at: Generated<Timestamp>;
}

export interface MockProviderState {
  fail_fetch: Generated<number>;
  fail_push: Generated<number>;
  integration_account_id: string;
  organization_id: string;
  updated_at: Generated<Timestamp>;
}

export interface OrderItems {
  amount: number;
  id: Generated<string>;
  name: string;
  order_id: string;
  organization_id: string;
  product_id: string;
  quantity: number;
  sort_order: Generated<number>;
  tax_amount: Generated<number>;
  tax_rate_bp: number;
  unit_price: number;
}

export interface Orders {
  attributed_staff_id: string | null;
  cancel_reason: string | null;
  cancelled_at: Timestamp | null;
  carrier: string | null;
  channel: Generated<string>;
  contact_email: string | null;
  contact_phone: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  customer_id: string | null;
  delivered_at: Timestamp | null;
  discount_total: Generated<number>;
  expires_at: Timestamp | null;
  id: Generated<string>;
  idempotency_key: string | null;
  is_subscription: Generated<boolean>;
  note: string | null;
  order_number: string;
  organization_id: string;
  paid_at: Timestamp | null;
  paid_payment_id: string | null;
  payment_attempts: Generated<number>;
  payment_failed_at: Timestamp | null;
  referral_link_id: string | null;
  refunded_amount: Generated<number>;
  shipped_at: Timestamp | null;
  shipping_address: Json | null;
  shipping_fee: Generated<number>;
  shop_id: string | null;
  status: Generated<string>;
  stock_released_at: Timestamp | null;
  subtotal: Generated<number>;
  tax_total: Generated<number>;
  total: Generated<number>;
  trace_id: string | null;
  tracking_number: string | null;
  updated_at: Generated<Timestamp>;
}

export interface Organizations {
  created_at: Generated<Timestamp>;
  currency: Generated<string>;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  invoice_registration_number: string | null;
  name: string;
  plan: Generated<string>;
  settings: Generated<Json>;
  slug: string;
  status: Generated<string>;
  timezone: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface OtpChallenges {
  attempts: Generated<number>;
  channel: string;
  code_hash: string;
  consumed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  destination: string;
  expires_at: Timestamp;
  id: Generated<string>;
  max_attempts: Generated<number>;
  organization_id: string | null;
  purpose: string;
  user_id: string | null;
}

export interface Payments {
  amount: number;
  change_amount: Generated<number>;
  client_secret: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  custom_method_id: string | null;
  failure_code: string | null;
  failure_reason: string | null;
  id: Generated<string>;
  idempotency_key: string;
  metadata: Generated<Json>;
  method: string;
  order_id: string | null;
  organization_id: string;
  provider: string | null;
  provider_payment_id: string | null;
  refunded_amount: Generated<number>;
  status: Generated<string>;
  succeeded_at: Timestamp | null;
  tendered_amount: number | null;
  trace_id: string | null;
  transaction_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface PointLedger {
  balance_after: number;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  customer_id: string;
  delta: number;
  expires_at: Timestamp | null;
  id: Generated<string>;
  note: string | null;
  organization_id: string;
  reason: string;
  transaction_id: string | null;
}

export interface Products {
  barcode: string | null;
  brand: string | null;
  category: string | null;
  cost: number | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  deleted_at: Timestamp | null;
  description: string | null;
  id: Generated<string>;
  image_file_ids: Generated<string[]>;
  is_online: Generated<boolean>;
  name: string;
  organization_id: string;
  price: number;
  price_tax_included: Generated<boolean>;
  shop_id: string | null;
  sku: string | null;
  status: Generated<string>;
  stock_managed: Generated<boolean>;
  tax_rate_bp: Generated<number>;
  trace_id: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface ProductStocks {
  id: Generated<string>;
  organization_id: string;
  product_id: string;
  quantity: Generated<number>;
  reorder_point: number | null;
  shop_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface Receipts {
  addressee: string | null;
  content: Json;
  id: Generated<string>;
  issued_at: Generated<Timestamp>;
  issued_by: string | null;
  organization_id: string;
  proviso: string | null;
  receipt_number: string;
  receipt_type: string;
  reissue_of: string | null;
  transaction_id: string;
}

export interface ReferralEvents {
  amount: number | null;
  appointment_id: string | null;
  created_at: Generated<Timestamp>;
  customer_id: string | null;
  event_type: string;
  id: Generated<string>;
  metadata: Generated<Json>;
  order_id: string | null;
  organization_id: string;
  referral_link_id: string;
}

export interface ReferralLinks {
  click_count: Generated<number>;
  code: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  customer_id: string | null;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  organization_id: string;
  shop_id: string | null;
  staff_id: string | null;
  target: Generated<string>;
  target_id: string | null;
  updated_at: Generated<Timestamp>;
  utm: Generated<Json>;
}

export interface Refunds {
  amount: number;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  idempotency_key: string;
  organization_id: string;
  payment_id: string;
  provider_refund_id: string | null;
  reason: string | null;
  register_session_id: string | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface RegisterCashMovements {
  amount: number;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  movement_type: string;
  organization_id: string;
  reason: string;
  register_session_id: string;
  staff_id: string | null;
}

export interface RegisterSessions {
  cash_breakdown: Json | null;
  closed_at: Timestamp | null;
  closed_by: string | null;
  counted_cash: number | null;
  created_at: Generated<Timestamp>;
  difference: number | null;
  expected_cash: number | null;
  id: Generated<string>;
  note: string | null;
  opened_at: Generated<Timestamp>;
  opened_by: string;
  opening_cash: Generated<number>;
  organization_id: string;
  shop_id: string;
  status: Generated<string>;
  summary: Json | null;
  updated_at: Generated<Timestamp>;
}

export interface Resources {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  name: string;
  organization_id: string;
  resource_type: string;
  shop_id: string;
  sort_order: Generated<number>;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface ReviewRequests {
  access_token_id: string | null;
  appointment_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  customer_id: string;
  id: Generated<string>;
  message_id: string | null;
  opened_at: Timestamp | null;
  organization_id: string;
  shop_id: string;
  staff_id: string | null;
  status: Generated<string>;
  submitted_at: Timestamp | null;
  transaction_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface Reviews {
  appointment_id: string | null;
  body: string | null;
  created_at: Generated<Timestamp>;
  customer_id: string | null;
  external_review_id: string | null;
  id: Generated<string>;
  integration_account_id: string | null;
  organization_id: string;
  posted_at: Generated<Timestamp>;
  rating: number;
  replied_at: Timestamp | null;
  replied_by: string | null;
  reply_body: string | null;
  reply_sync_error: string | null;
  reply_synced_at: Timestamp | null;
  review_request_id: string | null;
  reviewer_name: string | null;
  shop_id: string;
  source: Generated<string>;
  staff_id: string | null;
  staff_rating: number | null;
  status: Generated<string>;
  title: string | null;
  updated_at: Generated<Timestamp>;
}

export interface RolePermissions {
  organization_id: string | null;
  permission_key: string;
  role_id: string;
}

export interface Roles {
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  is_system: Generated<boolean>;
  key: string;
  name: string;
  organization_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface ScheduleBlocks {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  end_at: Timestamp;
  id: Generated<string>;
  organization_id: string;
  reason: string | null;
  resource_id: string | null;
  shop_id: string;
  source: Generated<string>;
  staff_id: string | null;
  start_at: Timestamp;
}

export interface Segments {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  description: string | null;
  id: Generated<string>;
  name: string;
  organization_id: string;
  rule: Json;
  updated_at: Generated<Timestamp>;
}

export interface ShopBusinessHours {
  close_time: string;
  id: Generated<string>;
  open_time: string;
  organization_id: string;
  shop_id: string;
  weekday: number;
}

export interface ShopCalendarExceptions {
  close_time: string | null;
  created_at: Generated<Timestamp>;
  date: string;
  id: Generated<string>;
  is_closed: Generated<boolean>;
  note: string | null;
  open_time: string | null;
  organization_id: string;
  shop_id: string;
}

export interface Shops {
  address_line: string | null;
  city: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  deleted_at: Timestamp | null;
  description: string | null;
  email: string | null;
  id: Generated<string>;
  name: string;
  organization_id: string;
  phone: string | null;
  postal_code: string | null;
  prefecture: string | null;
  public_booking_enabled: Generated<boolean>;
  settings: Generated<Json>;
  slug: string;
  status: Generated<string>;
  timezone: Generated<string>;
  trace_id: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface SnsAssets {
  caption: string | null;
  content: Generated<Json>;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  customer_consent: Generated<boolean>;
  deleted_at: Timestamp | null;
  file_id: string | null;
  hashtags: Generated<string[]>;
  id: Generated<string>;
  karte_asset_id: string | null;
  organization_id: string;
  review_id: string | null;
  shop_id: string | null;
  staff_id: string | null;
  template: string;
}

export interface StaffMenus {
  duration_min: number | null;
  menu_id: string;
  organization_id: string;
  price: number | null;
  staff_id: string;
}

export interface Staffs {
  color: Generated<string>;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  deleted_at: Timestamp | null;
  display_name: string;
  display_name_kana: string | null;
  email: string | null;
  employment_type: Generated<string>;
  hired_on: string | null;
  id: Generated<string>;
  is_bookable: Generated<boolean>;
  nomination_fee: Generated<number>;
  organization_id: string;
  phone: string | null;
  public_profile: Generated<Json>;
  public_slug: string | null;
  retired_on: string | null;
  role_id: string;
  sort_order: Generated<number>;
  status: Generated<string>;
  title: string | null;
  trace_id: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  user_id: string | null;
}

export interface StaffShifts {
  created_at: Generated<Timestamp>;
  date: string;
  end_time: string | null;
  id: Generated<string>;
  note: string | null;
  organization_id: string;
  shift_type: Generated<string>;
  shop_id: string;
  staff_id: string;
  start_time: string | null;
  updated_at: Generated<Timestamp>;
}

export interface StaffShopAssignments {
  created_at: Generated<Timestamp>;
  ended_on: string | null;
  id: Generated<string>;
  is_primary: Generated<boolean>;
  organization_id: string;
  shop_id: string;
  staff_id: string;
  started_on: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface StaffWeeklySchedules {
  end_time: string;
  id: Generated<string>;
  organization_id: string;
  shop_id: string;
  staff_id: string;
  start_time: string;
  weekday: number;
}

export interface StockMovements {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  delta: number;
  id: Generated<string>;
  note: string | null;
  order_id: string | null;
  organization_id: string;
  product_id: string;
  reason: string;
  shop_id: string | null;
  transaction_id: string | null;
}

export interface SyncConflicts {
  appointment_id: string | null;
  conflict_type: string;
  created_at: Generated<Timestamp>;
  details: Generated<Json>;
  external_booking_id: string | null;
  id: Generated<string>;
  organization_id: string;
  resolution: string | null;
  resolved_at: Timestamp | null;
  resolved_by: string | null;
  state: Generated<string>;
}

export interface SyncJobs {
  created_at: Generated<Timestamp>;
  cursor_after: string | null;
  cursor_before: string | null;
  error: string | null;
  finished_at: Timestamp | null;
  id: Generated<string>;
  integration_account_id: string;
  mode: string;
  organization_id: string;
  provider: string;
  resource: string;
  retry_count: Generated<number>;
  started_at: Timestamp | null;
  state: Generated<string>;
  stats: Generated<Json>;
  triggered_by: Generated<string>;
}

export interface Tags {
  color: Generated<string>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  organization_id: string;
}

export interface TransactionItems {
  allocated_discount: Generated<number>;
  amount: number;
  coupon_id: string | null;
  created_at: Generated<Timestamp>;
  details: Generated<Json>;
  id: Generated<string>;
  item_type: string;
  line_discount: Generated<number>;
  menu_id: string | null;
  name: string;
  net_amount: Generated<number>;
  organization_id: string;
  product_id: string | null;
  quantity: Generated<number>;
  returned_quantity: Generated<number>;
  sort_order: Generated<number>;
  tax_amount: Generated<number>;
  tax_rate_bp: Generated<number>;
  transaction_id: string;
  unit_price: number;
}

export interface TransactionItemStaff {
  allocated_amount: Generated<number>;
  id: Generated<string>;
  is_nominated: Generated<boolean>;
  organization_id: string;
  role: Generated<string>;
  share_bp: number;
  staff_id: string;
  transaction_item_id: string;
}

export interface Transactions {
  appointment_completed_by_tx: Generated<boolean>;
  appointment_id: string | null;
  change_total: Generated<number>;
  completed_at: Timestamp | null;
  completed_by: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  customer_id: string | null;
  discount_total: Generated<number>;
  id: Generated<string>;
  is_new_customer: boolean | null;
  is_nominated: Generated<boolean>;
  note: string | null;
  organization_id: string;
  paid_total: Generated<number>;
  point_earned: Generated<number>;
  point_used: Generated<number>;
  refunded_total: Generated<number>;
  register_session_id: string | null;
  shop_id: string;
  staff_id: string | null;
  status: Generated<string>;
  subtotal: Generated<number>;
  tax_breakdown: Generated<Json>;
  tax_total: Generated<number>;
  total: Generated<number>;
  trace_id: string | null;
  transaction_number: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  version: Generated<number>;
  void_reason: string | null;
  voided_at: Timestamp | null;
  voided_by: string | null;
}

export interface Users {
  auth_provider: Generated<string>;
  created_at: Generated<Timestamp>;
  display_name: string;
  email: string;
  failed_login_count: Generated<number>;
  id: Generated<string>;
  last_login_at: Timestamp | null;
  locked_until: Timestamp | null;
  mfa_enabled: Generated<boolean>;
  password_hash: string | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface WebhookEvents {
  attempts: Generated<number>;
  event_id: string;
  event_type: string | null;
  headers: Generated<Json>;
  id: Generated<string>;
  last_error: string | null;
  organization_id: string | null;
  payload: Json;
  processed_at: Timestamp | null;
  provider: string;
  received_at: Generated<Timestamp>;
  signature_valid: boolean;
  status: Generated<string>;
}

export interface DB {
  access_tokens: AccessTokens;
  ai_suggestions: AiSuggestions;
  analytics_daily_menu: AnalyticsDailyMenu;
  analytics_daily_shop: AnalyticsDailyShop;
  analytics_daily_source: AnalyticsDailySource;
  analytics_daily_staff: AnalyticsDailyStaff;
  appointment_events: AppointmentEvents;
  appointment_resources: AppointmentResources;
  appointment_services: AppointmentServices;
  appointments: Appointments;
  audit_logs: AuditLogs;
  auth_sessions: AuthSessions;
  automation_runs: AutomationRuns;
  automations: Automations;
  campaigns: Campaigns;
  counters: Counters;
  coupon_redemptions: CouponRedemptions;
  coupons: Coupons;
  custom_payment_methods: CustomPaymentMethods;
  customer_channel_preferences: CustomerChannelPreferences;
  customer_duplicate_dismissals: CustomerDuplicateDismissals;
  customer_identities: CustomerIdentities;
  customer_memos: CustomerMemos;
  customer_merge_logs: CustomerMergeLogs;
  customer_scores: CustomerScores;
  customer_shop_relations: CustomerShopRelations;
  customer_tags: CustomerTags;
  customers: Customers;
  data_exports: DataExports;
  domain_events: DomainEvents;
  external_bookings: ExternalBookings;
  external_slot_blocks: ExternalSlotBlocks;
  feature_flags: FeatureFlags;
  files: Files;
  form_responses: FormResponses;
  form_templates: FormTemplates;
  idempotency_keys: IdempotencyKeys;
  integration_accounts: IntegrationAccounts;
  jobs: Jobs;
  karte_assets: KarteAssets;
  karte_templates: KarteTemplates;
  kartes: Kartes;
  line_channels: LineChannels;
  menu_categories: MenuCategories;
  menu_resource_requirements: MenuResourceRequirements;
  menu_shop_overrides: MenuShopOverrides;
  menus: Menus;
  message_templates: MessageTemplates;
  messages: Messages;
  mock_provider_blocks: MockProviderBlocks;
  mock_provider_bookings: MockProviderBookings;
  mock_provider_state: MockProviderState;
  order_items: OrderItems;
  orders: Orders;
  organizations: Organizations;
  otp_challenges: OtpChallenges;
  payments: Payments;
  point_ledger: PointLedger;
  product_stocks: ProductStocks;
  products: Products;
  receipts: Receipts;
  referral_events: ReferralEvents;
  referral_links: ReferralLinks;
  refunds: Refunds;
  register_cash_movements: RegisterCashMovements;
  register_sessions: RegisterSessions;
  resources: Resources;
  review_requests: ReviewRequests;
  reviews: Reviews;
  role_permissions: RolePermissions;
  roles: Roles;
  schedule_blocks: ScheduleBlocks;
  segments: Segments;
  shop_business_hours: ShopBusinessHours;
  shop_calendar_exceptions: ShopCalendarExceptions;
  shops: Shops;
  sns_assets: SnsAssets;
  staff_menus: StaffMenus;
  staff_shifts: StaffShifts;
  staff_shop_assignments: StaffShopAssignments;
  staff_weekly_schedules: StaffWeeklySchedules;
  staffs: Staffs;
  stock_movements: StockMovements;
  sync_conflicts: SyncConflicts;
  sync_jobs: SyncJobs;
  tags: Tags;
  transaction_item_staff: TransactionItemStaff;
  transaction_items: TransactionItems;
  transactions: Transactions;
  users: Users;
  webhook_events: WebhookEvents;
}
